### ISSUE TITLE
Fix travis badge in `/docs/`

### ISSUE THREAD

**Issue by willdurand** [geocoder-php/geocoder-php.github.io#17]
URL: https://geocoder-php.org/docs/

The travis-ci badge does not load for me:

![Screen Shot 2019-08-26 at 14 34 38](https://user-images.githubusercontent.com/217628/63691135-b8fa0080-c80e-11e9-8c52-598e72d096c1.png)

**Comment by atymic** [comment]
Hmm, it works for me. Could you check your dev console for errors/404s?

![image](https://user-images.githubusercontent.com/50683531/63726310-46396580-c8a0-11e9-8507-03023b6543d4.png)

**Comment by atymic** [comment]
Oh, my bad. It's the badge on the docs. It still works for me though:

![image](https://user-images.githubusercontent.com/50683531/63726375-6bc66f00-c8a0-11e9-9df4-e6ee0761089f.png)

**Comment by willdurand** [comment]
ahm, ok. Maybe I have a local issue then..

**Comment by atymic** [comment]
PR open here to switch it to a travis badge:
https://github.com/geocoder-php/Geocoder/pull/1009
