### ISSUE TITLE
No emoji in "Local" section

### ISSUE THREAD

**Issue by willdurand** [geocoder-php/geocoder-php.github.io#18]
URL: https://geocoder-php.org/docs/ (Local section)

We should display flags but it does not work because we're not using emoji, we're using the GitHub syntax to render emoji:

![Screen Shot 2019-08-26 at 14 34 28](https://user-images.githubusercontent.com/217628/63691168-cca56700-c80e-11e9-9da1-1f78ce2cfffc.png)

**Comment by atymic** [comment]
Good catch. Will look into that :)

**Comment by atymic** [comment]
Pr'd in #19 if you want to have a look.
